# -*- coding: utf-8 -*-
"""WSC assignment4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MPcQH3a9C0ceCZKoF9Di1nkcR-IJF-2E

<p><img alt="Colaboratory logo" height="45px" src="/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>

<h1>What is Colaboratory?</h1>

Colaboratory, or "Colab" for short, allows you to write and execute Python in your browser, with 
- Zero configuration required
- Free access to GPUs
- Easy sharing

Whether you're a **student**, a **data scientist** or an **AI researcher**, Colab can make your work easier. Watch [Introduction to Colab](https://www.youtube.com/watch?v=inN8seMm7UI) to learn more, or just get started below!

## **Getting started**

The document you are reading is not a static web page, but an interactive environment called a **Colab notebook** that lets you write and execute code.

For example, here is a **code cell** with a short Python script that computes a value, stores it in a variable, and prints the result:
"""

seconds_in_a_day = 24 * 60 * 60
seconds_in_a_day

"""To execute the code in the above cell, select it with a click and then either press the play button to the left of the code, or use the keyboard shortcut "Command/Ctrl+Enter". To edit the code, just click the cell and start editing.

Variables that you define in one cell can later be used in other cells:
"""

seconds_in_a_week = 7 * seconds_in_a_day
seconds_in_a_week

"""Colab notebooks allow you to combine **executable code** and **rich text** in a single document, along with **images**, **HTML**, **LaTeX** and more. When you create your own Colab notebooks, they are stored in your Google Drive account. You can easily share your Colab notebooks with co-workers or friends, allowing them to comment on your notebooks or even edit them. To learn more, see [Overview of Colab](/notebooks/basic_features_overview.ipynb). To create a new Colab notebook you can use the File menu above, or use the following link: [create a new Colab notebook](http://colab.research.google.com#create=true).

Colab notebooks are Jupyter notebooks that are hosted by Colab. To learn more about the Jupyter project, see [jupyter.org](https://www.jupyter.org).

## Data science

With Colab you can harness the full power of popular Python libraries to analyze and visualize data. The code cell below uses **numpy** to generate some random data, and uses **matplotlib** to visualize it. To edit the code, just click the cell and start editing.
"""

import numpy as np
from matplotlib import pyplot as plt

ys = 200 + np.random.randn(100)
x = [x for x in range(len(ys))]

plt.plot(x, ys, '-')
plt.fill_between(x, ys, 195, where=(ys > 195), facecolor='g', alpha=0.6)

plt.title("Sample Visualization")
plt.show()

"""You can import your own data into Colab notebooks from your Google Drive account, including from spreadsheets, as well as from Github and many other sources. To learn more about importing data, and how Colab can be used for data science, see the links below under [Working with Data](#working-with-data).

## Machine learning

With Colab you can import an image dataset, train an image classifier on it, and evaluate the model, all in just [a few lines of code](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb). Colab notebooks execute code on Google's cloud servers, meaning you can leverage the power of Google hardware, including [GPUs and TPUs](#using-accelerated-hardware), regardless of the power of your machine. All you need is a browser.

Colab is used extensively in the machine learning community with applications including:
- Getting started with TensorFlow
- Developing and training neural networks
- Experimenting with TPUs
- Disseminating AI research
- Creating tutorials

To see sample Colab notebooks that demonstrate machine learning applications, see the [machine learning examples](#machine-learning-examples) below.

## More Resources

### Working with Notebooks in Colab
- [Overview of Colaboratory](/notebooks/basic_features_overview.ipynb)
- [Guide to Markdown](/notebooks/markdown_guide.ipynb)
- [Importing libraries and installing dependencies](/notebooks/snippets/importing_libraries.ipynb)
- [Saving and loading notebooks in GitHub](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb)
- [Interactive forms](/notebooks/forms.ipynb)
- [Interactive widgets](/notebooks/widgets.ipynb)
- <img src="/img/new.png" height="20px" align="left" hspace="4px" alt="New"></img>
 [TensorFlow 2 in Colab](/notebooks/tensorflow_version.ipynb)

<a name="working-with-data"></a>
### Working with Data
- [Loading data: Drive, Sheets, and Google Cloud Storage](/notebooks/io.ipynb) 
- [Charts: visualizing data](/notebooks/charts.ipynb)
- [Getting started with BigQuery](/notebooks/bigquery.ipynb)

### Machine Learning Crash Course
These are a few of the notebooks from Google's online Machine Learning course. See the [full course website](https://developers.google.com/machine-learning/crash-course/) for more.
- [Intro to Pandas](/notebooks/mlcc/intro_to_pandas.ipynb)
- [Tensorflow concepts](/notebooks/mlcc/tensorflow_programming_concepts.ipynb)
- [First steps with TensorFlow](/notebooks/mlcc/first_steps_with_tensor_flow.ipynb)
- [Intro to neural nets](/notebooks/mlcc/intro_to_neural_nets.ipynb)
- [Intro to sparse data and embeddings](/notebooks/mlcc/intro_to_sparse_data_and_embeddings.ipynb)

<a name="using-accelerated-hardware"></a>
### Using Accelerated Hardware
- [TensorFlow with GPUs](/notebooks/gpu.ipynb)
- [TensorFlow with TPUs](/notebooks/tpu.ipynb)

<a name="machine-learning-examples"></a>

## Machine Learning Examples

To see end-to-end examples of the interactive machine learning analyses that Colaboratory makes possible, check out these  tutorials using models from [TensorFlow Hub](https://tfhub.dev).

A few featured examples:

- [Retraining an Image Classifier](https://tensorflow.org/hub/tutorials/tf2_image_retraining): Build a Keras model on top of a pre-trained image classifier to distinguish flowers.
- [Text Classification](https://tensorflow.org/hub/tutorials/tf2_text_classification): Classify IMDB movie reviews as either *positive* or *negative*.
- [Style Transfer](https://tensorflow.org/hub/tutorials/tf2_arbitrary_image_stylization): Use deep learning to transfer style between images.
- [Multilingual Universal Sentence Encoder Q&A](https://tensorflow.org/hub/tutorials/retrieval_with_tf_hub_universal_encoder_qa): Use a machine learning model to answer questions from the SQuAD dataset.
- [Video Interpolation](https://tensorflow.org/hub/tutorials/tweening_conv3d): Predict what happened in a video between the first and the last frame.

1. Summary
"""

import networkx as nx
import matplotlib.pyplot as plt
G1 = nx.read_edgelist("datasetPrepare.txt",create_using=nx.DiGraph(), nodetype = int)
print(nx.info(G1))

"""2.Degree Centrality"""

import operator
Degree_centrality=nx.degree_centrality(G1) # the fuction ddegree_centrality(G) Compute the degree centrality for nodes and returns Dictionary of nodes with degree centrality as the value.
#Degree_centrality #Dictionary that contains Degree Centrality Values
minimum=sorted(Degree_centrality.keys(), key=lambda key:Degree_centrality[key], reverse=False)[0]
maximum=sorted(Degree_centrality.keys(),key=lambda key:Degree_centrality[key], reverse=True)[0]
print("minimum degree centrality node and value",minimum,Degree_centrality[minimum]) #minimum degree centrality
print("maximum degree centrality node and value",maximum,Degree_centrality[maximum]) #maximum degree centrality
print("nodes in Decreasing order of Degree Centrality(top 5 nodes):\n") 
sorted(Degree_centrality.items(),key=operator.itemgetter(1),reverse=True)[0:5]

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
# Data for plotting
t = list(Degree_centrality.keys())
s = list(Degree_centrality.values())
plt.plot(t, s,'ro')
plt.xlabel('Nodes')
plt.ylabel('Degree Centrality')
plt.grid()

"""3.Closeness Centrality"""

Closeness_Centrality=nx.closeness_centrality(G1) #the function closeness_centrality(G, u=None, distance=None, normalized=True) Compute closeness centrality for nodes and Dictionary of nodes with closeness centrality as the value.
#Closeness_Centrality #Dictionary of nodes with closeness centrality as the value.
minimum=sorted(Closeness_Centrality.keys(), key=lambda key:Closeness_Centrality[key], reverse=False)[0]
maximum=sorted(Closeness_Centrality.keys(), key=lambda key:Closeness_Centrality[key], reverse=True)[0]
print("minimum Closeness centrality node and value",minimum,Closeness_Centrality[minimum]) #minimum Closeness Centrality
print("maximum Closeness centrality node and value",maximum,Closeness_Centrality[maximum]) #maximum Closeness Centrality
print("nodes in Decreasing order of Closeness Centrality(top 5 nodes):\n")
sorted(Closeness_Centrality.items(),key=operator.itemgetter(1),reverse=True)[0:5]

# Data for plotting
t = list(Closeness_Centrality.keys())
s = list(Closeness_Centrality.values())
plt.plot(t, s,'ro')
plt.xlabel('Nodes')
plt.ylabel('Closeness Centrality')
plt.grid()

"""4.Betweenness Centrality"""

Betweenness_Centrality=nx.betweenness_centrality(G1,normalized=True, weight=None, endpoints=False, seed=None) #The funcion betweenness_centrality(G, k=None, normalized=True, weight=None, endpoints=False, seed=None) computes Compute the shortest-path betweenness centrality for nodes and returns Dictionary of nodes with betweenness centrality as the value.
#Betweenness_Centrality #Dictionary of nodes with betweenness centrality as the value.
minimum=sorted(Betweenness_Centrality.keys(), key=lambda key:Betweenness_Centrality[key], reverse=False)[0]
maximum=sorted(Betweenness_Centrality.keys(), key=lambda key:Betweenness_Centrality[key], reverse=True)[0]
print("minimum Betweenness centrality node and value",minimum,Betweenness_Centrality[minimum])
print("maximum Betweenness centrality node and value",maximum,Betweenness_Centrality[maximum])
print("nodes in Decreasing order of Betweenness Centrality(top 5 nodes):\n")
sorted(Betweenness_Centrality.items(),key=operator.itemgetter(1),reverse=True)[0:5]

# Data for plotting
t = list(Betweenness_Centrality.keys())
s = list(Betweenness_Centrality.values())
plt.plot(t, s,'ro')
plt.xlabel('Nodes')
plt.ylabel('Betweenness Centrality')
plt.grid()

"""5.Eigen Vector Centrality"""

Eigenvector_Centrality=nx.eigenvector_centrality(G1, max_iter=100, tol=1e-06, nstart=None, weight=None) #The function eigenvector_centrality(G, max_iter=100, tol=1e-06, nstart=None, weight='weight') Compute the eigenvector centrality for the graph G and return Dictionary of nodes with eigenvector centrality as the value.
#Eigenvector_Centrality #Dictionary of nodes with eigenvector centrality as the value.
minimum=sorted(Eigenvector_Centrality.keys(), key=lambda key:Eigenvector_Centrality[key], reverse=False)[0]
maximum=sorted(Eigenvector_Centrality.keys(), key=lambda key:Eigenvector_Centrality[key], reverse=True)[0]
print("minimum degree centrality node and value",minimum,Eigenvector_Centrality[minimum])
print("maximum degree centrality node and value",maximum,Eigenvector_Centrality[maximum])
print("nodes in Decreasing order of Eigenvector Centrality(top 5 nodes):\n")
sorted(Eigenvector_Centrality.items(),key=operator.itemgetter(1),reverse=True)[0:5]

# Data for plotting
t = list(Eigenvector_Centrality.keys())
s = list(Eigenvector_Centrality.values())
plt.plot(t, s,'ro')
plt.xlabel('Nodes')
plt.ylabel('Eigenvector Centrality')
plt.grid()

"""6.PageRank algorithm"""

pr1 = nx.pagerank(G1, alpha=0.85)
#print("page rank:G1",pr1) #page rank of all the webpages
maximum=sorted(pr1.keys(), key=lambda key:pr1[key], reverse=True)[0] 
minimum=sorted(pr1.keys(), key=lambda key:pr1[key], reverse=False)[0]
print("maximum page rank webpage",maximum,pr1[maximum]) # maximum page rank webpage
print("minimum page rank webpage",minimum,pr1[minimum])#minimum page rank webpage
print("nodes in Decreasing order of Page Rank (top 5 nodes):\n")
sorted(pr1.items(),key=operator.itemgetter(1),reverse=True)[0:5]

# Data for plotting
t = list(pr1.keys())
s = list(pr1.values())
plt.plot(t, s,'ro')
plt.xlabel('Nodes')
plt.ylabel('Pagerank')
plt.grid()

"""7.Degree Distribution"""

def plot_degree_distribution(G1):
  all_degree=dict(nx.degree(G1)).values()
 
  unique_degree=list(set(all_degree))
  count_degree=[]
  all_degree=list(all_degree)
  for i in unique_degree:
    x=all_degree.count(i)
    count_degree.append(x)
  
  
  #print(count_degree)
  plt.plot(unique_degree,count_degree,'yo-')
  plt.xlabel('Degrees')
  plt.ylabel('No of nodes ')
  plt.title('Degree distribution of Peer to peer network Gnutella')
  plt.show()
plot_degree_distribution(G1)

"""8.Diameter"""

print (nx.diameter(G1))

9.Geodesic path length

E=nx.read_edgelist("datasetPrepare.txt")
print("Example shortest path: ")
print(nx.shortest_path_length(E,source="1",target="29"))
E = nx.path_graph("/content/p2p-Gnutella09.txt")
print("Avg. shortest path length: ")
print(nx.average_shortest_path_length(E))

"""10.Clustering coefficient & average clustering coefficient"""

E = nx.read_edgelist("datasetPrepare.txt")
print("Clustering coefficient: ")
for i in nx.clustering(E).items():
  print (i)
print ("Avg clustering coefficient: ")
print (nx.average_clustering(E))